language: node_js

node_js:
  - "6"

services:
  - postgresql

before_install:
  - npm install -g mocha
  - npm install -g sequelize-cli

before_script:
  - sequelize db:migrate && sequelize db:seed:all

script:
  - npm test
