language: node_js

node_js:
  - "6"

services:
  - postgresql

before_install:
  - npm install -g mocha
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - npm test
